apiVersion: v1
kind: Service
metadata:
  name: gravity-log-web-service
spec:
  type: NodePort
  selector:
    app: gravity-log-web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
